### PR TITLE
add libsensors-iio

### PR DESCRIPTION
**Pull request by Icenowy**
This is based on Intel's implementation.

Signed-off-by: Icenowy Zheng <icenowy@aosc.io>

### CODE REVIEW

**Comment by rsglobal** [comment]
Thanks for the contribution.

Could you tell a little bit more where this sources came from?
Did you modified it or used as is?

Can we replace it with https://github.com/intel/android-iio-sensors-hal ?

**Comment by Icenowy** [comment]
This is from https://zh.osdn.net/projects/android-x86/scm/git/hardware-intel-libsensors/commits?branch=pie-x86 , modified to build on Q and added support for multiple mount matrix types.

**Comment by rsglobal** [comment]
Thank you for the clarification.

Could we replace this single-commit PR with the following:
1. Fork https://github.com/robherring/android-iio-sensors-hal
2. Apply required changes on top
3. Send PR to Rob for review
4. I'll pick it into glodroid_forks while reviewing, and when merged switch manifest to Rob's repository.

**Comment by Icenowy** [comment]
https://github.com/robherring/android-iio-sensors-hal/pull/2

**Comment by rsglobal** [comment]
Added to manifest:
https://github.com/glodroid/glodroid_manifest/commit/e69e47d605b4bf92d64c961cad6268a1e52072ae

Thanks!

**Pull request closed without merging**
